INSERT INTO EMPLOYEE (ID, FNAME, LNAME, DESIGNATION, EMAIL, MOBILE, PASS)
VALUES (100, 'TOM', 'SINGH', 'PROGRAMMER', 'TOMMY@rediff.com', '9999999999','QWER');
INSERT INTO EMPLOYEE (ID, FNAME, LNAME, DESIGNATION, EMAIL, MOBILE, PASS)
VALUES (101, 'HEM', 'kapoor', 'PROJECT ASSOCIATE', 'hem@yahoo.com', '8888888888','WERT');
INSERT INTO EMPLOYEE (ID, FNAME, LNAME, DESIGNATION, EMAIL, MOBILE, PASS)
VALUES (102, 'Kareena', 'kapoor', 'System Engineer', 'kareena@gmail.com', '7777777777','ERTY');
INSERT INTO EMPLOYEE (ID, FNAME, LNAME, DESIGNATION, EMAIL, MOBILE, PASS)
VALUES (103, 'Akash', 'chaudhary', 'SALES FORCE DEVELOPER', 'akash@hotmail.COM', '6666666666','RTYU');
INSERT INTO EMPLOYEE (ID, FNAME, LNAME, DESIGNATION, EMAIL, MOBILE,PASS)
VALUES (104, 'Anubhav', 'gupta', 'ENGINEER', 'anubhav@outlook.COM', '5555555555','TURY');

INSERT INTO EMPLOYEE_LOGIN (ID,PASS)
VALUES (104, 'TURY');